<svelte:head>
	<title>About</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<section>
	<div class="text-column">
		<h1>AI Language Learning Quiz App</h1>
		<p>
			This app implements a simple language learning exercise — a series of multiple choice questions where the user must select the correct translation of a given word.
			The twist here is that on the back-end, all the data for the questions is being generated by a Large Language Model — no human translators needed.
		</p>
		<p>
			Navigate to the <a href="/quiz">Quiz</a> page to start.
		</p>
	</div>
</section>

<style>
	section {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		flex: 0.6;
	}

	h1 {
		width: 100%;
	}
</style>
